### ISSUE TITLE
backend='auto' - leads to Ratelimit

### ISSUE THREAD

**Issue by sakjif** [deedy5/duckduckgo_search#272]
**Before you open an issue:**
- [x] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [x] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [x] https://duckduckgo.com is accessible in my browser
- [x] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug
I encountered an issue with limits in version 6.3.7. I decided to update to the latest version. Previously, I used backend=html for my requests, but after the update, I switched to backend=auto. However, the problem persists. I have to make several attempts to get a response, and there's no guarantee I'll get one in the end. I assumed the issue might be with the proxy. I replaced the proxy and also tried working without a proxy, but the problem still remains.

3 type of RateLimit responce:
```INFO - Error to search using lite backend: https://lite.duckduckgo.com/lite/ 202 Ratelimit```
```INFO - Error to search using html backend: https://html.duckduckgo.com/html 202 Ratelimit```
```INFO - Error to search using ecosia backend: https://www.ecosia.org/search?q=%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%82%D0%BF%D0%BB%D0%B5%D0%B9%D1%81+%D0%92%D0%91+%D0%90%D0%A0%D0%A2%D0%98%D0%9A%D0%A3%D0%9B+%22149751876%22+site%3Avk.com 403 Ratelimit```

**Steps to reproduce the problem:**
                   ```ddgs = DDGS(proxy=proxy, headers=headers, verify=False)```
 ```ddg_response = ddgs.text(keywords=request, safesearch='off', max_results=None, backend='auto')```

**Specify this information**

 - OS ubuntu/linux
 - environment
 - duckduckgo_search version 7.1.1

**Comment by deedy5** [comment]
fixed in v7.2.0

**Comment by Devy99** [comment]
Hi @deedy5 , I upgraded duckduckgo-search to v7.2.0 (and also the latest versions) but still face RateLimit at each request. Any suggestion?

**Comment by sakjif** [comment]
> Hi @deedy5 , I upgraded duckduckgo-search to v7.2.0 (and also to the latest versions) but still face RateLimit at each request. Any suggestion? 

could you show how you make a request?

**Comment by almirb** [comment]
I also having RateLimit errors searching like this:
```
headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
            }
            search_query = f"{domain} CNPJ"
            results = DDGS(headers=headers).text(search_query, region="br-pt",  safesearch='Off', timelimit='y', backend="lite", max_results=3)
.....
```
I put a time.sleep(1) between de commands, but continue to trigger RateLimit error:
``` 
INFO - Error to search using lite backend: https://lite.duckduckgo.com/lite/ 202 Ratelimit
````

What is the real DuckDuckGo API safe limit rate?

Thanks!
